// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_constrained_indices_cpp
IntegerVector get_constrained_indices_cpp(IntegerVector doy, IntegerVector hod, int day_win, int hour_win);
RcppExport SEXP _deweather_get_constrained_indices_cpp(SEXP doySEXP, SEXP hodSEXP, SEXP day_winSEXP, SEXP hour_winSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type doy(doySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type hod(hodSEXP);
    Rcpp::traits::input_parameter< int >::type day_win(day_winSEXP);
    Rcpp::traits::input_parameter< int >::type hour_win(hour_winSEXP);
    rcpp_result_gen = Rcpp::wrap(get_constrained_indices_cpp(doy, hod, day_win, hour_win));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_deweather_get_constrained_indices_cpp", (DL_FUNC) &_deweather_get_constrained_indices_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_deweather(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
