# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_constrained_indices_cpp <- function(doy, hod, day_win, hour_win) {
    .Call(`_deweather_get_constrained_indices_cpp`, doy, hod, day_win, hour_win)
}

